-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 23:34:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema job
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema job
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `job` DEFAULT CHARACTER SET utf8 ;
USE `job` ;

-- -----------------------------------------------------
-- Table `job`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`jobs` (
  `idjobs` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(50) NULL,
  `title` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `location` VARCHAR(100) NULL,
  `salary` MEDIUMINT(11) NULL,
  `uid` INT(11) NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  PRIMARY KEY (`idjobs`),
  UNIQUE INDEX `idjobs_UNIQUE` (`idjobs` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job`.`jobs_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`jobs_categories` (
  `idjobs_categories` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(50) NULL,
  PRIMARY KEY (`idjobs_categories`),
  UNIQUE INDEX `idjobs_categories_UNIQUE` (`idjobs_categories` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `job`.`jobs_cats_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`jobs_cats_relation` (
  `jobs_idjobs` INT(11) NOT NULL,
  `jobs_categories_idjobs_categories` INT NOT NULL,
  INDEX `fk_jobs_cats_relation_jobs_idx` (`jobs_idjobs` ASC),
  INDEX `fk_jobs_cats_relation_jobs_categories1_idx` (`jobs_categories_idjobs_categories` ASC),
  CONSTRAINT `fk_jobs_cats_relation_jobs`
    FOREIGN KEY (`jobs_idjobs`)
    REFERENCES `job`.`jobs` (`idjobs`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jobs_cats_relation_jobs_categories1`
    FOREIGN KEY (`jobs_categories_idjobs_categories`)
    REFERENCES `job`.`jobs_categories` (`idjobs_categories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job`.`resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`resume` (
  `idresume` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `skills` TEXT NULL,
  `uid` INT(11) NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  PRIMARY KEY (`idresume`),
  UNIQUE INDEX `idresume_UNIQUE` (`idresume` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job`.`resume_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`resume_work` (
  `idresume_work` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `date_job` VARCHAR(50) NULL,
  `resume_idresume` INT NOT NULL,
  PRIMARY KEY (`idresume_work`),
  INDEX `fk_resume_work_resume1_idx` (`resume_idresume` ASC),
  CONSTRAINT `fk_resume_work_resume1`
    FOREIGN KEY (`resume_idresume`)
    REFERENCES `job`.`resume` (`idresume`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job`.`resume_education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`resume_education` (
  `idresume_education` INT NOT NULL AUTO_INCREMENT,
  `education_name` VARCHAR(100) NULL,
  `faculty` VARCHAR(50) NULL,
  `resume_idresume` INT NOT NULL,
  PRIMARY KEY (`idresume_education`),
  INDEX `fk_resume_education_resume1_idx` (`resume_idresume` ASC),
  CONSTRAINT `fk_resume_education_resume1`
    FOREIGN KEY (`resume_idresume`)
    REFERENCES `job`.`resume` (`idresume`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `job`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
